version: '3'

networks:
  bc:

services:
  palethe:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - ganache
    networks:
      - bc
    environment:
    - FALLBACK_IP=192.168.20.41
  
  ganache:
    image: "trufflesuite/ganache-cli:latest"
    ports:
      - "8545:8545"
    networks:
      - bc
